### ISSUE TITLE
Rapp Manager : 'rocon_apps/chirp' is not unique and has no preferred rapp. rocon_apps/meow_chirp' has been selected.

### ISSUE THREAD

**Issue by wangzhaodong123** [RobustFieldAutonomyLab/turtlebot_exploration_3d#5] opened 2018-10-30 03:11 UTC
Hello, I ran your code successfully before, but i met an error these days. 

1. When i run "roslaunch turtlebot_exploration_3d minimal_explo.launch", it shows a [WARN]:
setting /run_id to cb9f3338-dbef-11e8-a8ab-00367664b761
process[rosout-1]: started with pid [11178]
started core service [/rosout]
process[robot_state_publisher-2]: started with pid [11196]
process[diagnostic_aggregator-3]: started with pid [11197]
process[mobile_base_nodelet_manager-4]: started with pid [11198]
process[mobile_base-5]: started with pid [11205]
process[bumper2pointcloud-6]: started with pid [11214]
process[cmd_vel_mux-7]: started with pid [11220]
process[turtlebot_laptop_battery-8]: started with pid [11222]
process[capability_server-9]: started with pid [11232]
process[app_manager-10]: started with pid [11240]
process[master-11]: started with pid [11252]
process[interactions-12]: started with pid [11276]
process[zeroconf/zeroconf-13]: started with pid [11285]
[ INFO] [1540868361.765459318]: Zeroconf: service successfully established [turtlebot][_ros-master._tcp][11311]
[WARN] [WallTime: 1540868363.614965] Rapp Manager : 'rocon_apps/chirp' is not unique and has no preferred rapp. rocon_apps/meow_chirp' has been selected.

2. When i run "roslaunch turtlebot_exploration_3d turtlebot_gmapping.launch", it can not find kinect:
[ INFO] [1540868420.788991651]: Initializing nodelet with 4 worker threads.
[ INFO] [1540868421.179178675]: Using plugin "static_layer"
[ INFO] [1540868421.218580597]: Requesting the map...
[ INFO] [1540868422.140915631]: No matching device found.... waiting for devices. Reason: std::string openni2_wrapper::OpenNI2Driver::resolveDeviceURI(const string&) @ /tmp/binarydeb/ros-indigo-openni2-camera-0.3.0/src/openni2_i2_driver.cpp @ 7 @ 737 : Invalid device number 1, there are 0 devices connected.

Waiting for your help, thank you.

**Comment by abhileshborode** [comment] 2018-10-31 04:01
Met the same issue on kinetic

**Comment by baishibona** [comment] 2018-11-10 01:47
Sorry for my late reply, for the "2nd" problem it seems like the driver of the Kinect sensor, this could happen for many reasons and most of the time the easiest fix is to reinstall the driver...unfortunately... 
For the first one, I am not sure what is the cause, however since it is a "WARN", is it affecting the mapping motions?

**Comment by wangzhaodong123** [comment] 2018-11-10 07:28
> Sorry for my late reply, for the "2nd" problem it seems like the driver of the Kinect sensor, this could happen for many reasons and most of the time the easiest fix is to reinstall the driver...unfortunately...
> For the first one, I am not sure what is the cause, however since it is a "WARN", is it affecting the mapping motions?

For the first problem, I find that when I run "roslaunch turtlebot_bringup minimal.launch" before running "minimal_explo.launch", the [WARN] will disapper.
So I compare "minimal_explo.launch" with "minimal.launch". The diferrence between the two is "<arg name="rapp_preferred_configuration_file" default="$(find turtlebot_bringup)/param/preferred_rapp.yaml" doc="a configuration of preferred rapps"/>" . "minimal_explo.launch"  does not include this arg.
I wonder if it lacks this arg?

**Comment by baishibona** [comment] 2019-03-05 04:35
sorry, your previous post did not show the "arg" you were referring to.
Seems you have solved the problem, so I am closing this ticket.
Feel free to reopen if you run into same errors again or just open a new one if you run into a new error.
Thanks.

**Closed as completed** 2019-03-05 04:35 UTC
